language: python
sudo: false
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: pypy
    - python: pypy3
    - python: 2.7
      env:
          - PURE_PYTHON=1
install:
    - pip install -U pip
    - pip install -U setuptools
    - pip install -U coverage coveralls
    - pip install -e .[test,docs]
script:
    - coverage run -m zope.testrunner --test-path=src
    - sphinx-build                         -b html    -d docs/_build/doctrees docs docs/_build/html
    - coverage run -a `which sphinx-build` -b doctest -d docs/_build/doctrees docs docs/_build/doctest

after_success:
    - coveralls

notifications:
    email: false
cache: pip
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
