language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy
install:
    - pip install -U pip
    - pip install -U setuptools
    - pip install -U zope.testrunner
    - pip install -e .[test]
script:
    - zope-testrunner --test-path=src
notifications:
    email: false
cache: pip
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
